### ISSUE TITLE
Semantic error: 'where' operator: Failed to resolve table or column expression named 'Costs_v1_2'

### ISSUE THREAD

**Issue by radutta-1972** [microsoft/finops-toolkit#1776]
Unable to ingest the report, seems its missing the table or column expression named 'Costs_v1_2' for the Hub.  Need help to fix this issue

**Comment by MSBrett** [comment]
@radutta-1972 - Fabric or ADX as the backend?

**Comment by MSBrett** [comment]
@radutta-1972 - try this version - should fix it.

[finops-hub-fabric-setup-Ingestion.txt](https://github.com/user-attachments/files/21372887/finops-hub-fabric-setup-Ingestion.txt)

**Comment by lundejd** [comment]
I got the Event House updated with no errors but still get this when using your Power BI files:

<img width="808" height="197" alt="Image" src="https://github.com/user-attachments/assets/a0ef91c4-b44c-4be4-a119-9b5ab474b602" />

**Comment by lundejd** [comment]
This allowed the Event House databases to complete without error. However, they are not consistent and Power BI still gives an error. is this normal?

<img width="255" height="727" alt="Image" src="https://github.com/user-attachments/assets/efae14f5-0a36-4e93-abd9-e03c895c38ac" />

<img width="268" height="707" alt="Image" src="https://github.com/user-attachments/assets/f8ac9f76-61a9-4829-90d2-78f14215be82" />

<img width="793" height="190" alt="Image" src="https://github.com/user-attachments/assets/e6185690-be27-4615-9635-d4dc18627baa" />

**Comment by radutta-1972** [comment]
@MSBrett Its the same error, I am using ADX for the dashboard/backend, please advise:

**Semantic error: 'where' operator: Failed to resolve table or column expression named 'Costs_v1_2'**

**Comment by flanakin** [comment]
#needs-info

**Comment by flanakin** [comment]
This should have been resolved in v13. Please let us know if you continue to have issues.
